services:
  timegan-pytorch:
    build:
      context: .
      args:
        UID: ${UID}
        GID: ${GID}
        COMMANDS_PATH: ${COMMANDS_PATH}
    working_dir: /timegan-pytorch
    volumes:
      - ./:/timegan-pytorch
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
    command: ${COMMANDS_PATH}
    ulimits:
      memlock: -1
      stack: 67108864
    ipc: host