services:
  timegan-pytorch:
    build:
      context: .
      args:
        UID: ${UID}
        GID: ${GID}
        COMMANDS_PATH: ${COMMANDS_PATH}
    working_dir: /timegan-pytorch
    volumes:
      - ./:/timegan-pytorch
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    command: ${COMMANDS_PATH}